workflows:
  flutter-ios:
    name: RDC-Services iOS
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Recreate folders
        script: |
          if [ ! -d "ios" ]; then
            flutter create --platforms=ios . --project-name rdc_services
          fi
          if [ ! -d "android" ]; then
            flutter create --platforms=android . --project-name rdc_services
          fi
      - name: Get packages
        script: |
          flutter pub get
          cd ios && pod install && cd ..
      - name: Build IPA no signing
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r app-release.ipa Payload
    artifacts:
      - build/ios/iphoneos/*.ipa
